data_path: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/apass5/AO2D_CustomV0s_HadronPID.root"
mc_path: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/mc/apass5/LHC25g11_G4list/AO2D_CustomV0s.root"
tree_name_data: "O2hypcands"
tree_name_mc: "O2mchypcands"
snapshot_dir: "../../SnapShotsData/LHC23_PbPb_pass5_CustomV0s_HadronPID"
model_dir: "../../Outputs/MLProcess/LHC23_PbPb_pass5_CustomV0s_HadronPID/TrainedModels"
QA_dir: "../../Outputs/MLProcess/LHC23_PbPb_pass5_CustomV0s_HadronPID/QAPlots"
WP_dir: "../../Outputs/MLProcess/LHC23_PbPb_pass5_CustomV0s_HadronPID/WorkingPoint"
Mix_mode: true
side_band_edges: [2.95, 3.02]

pt_bins: [2, 3, 4, 5.5, 8]
ct_bins: [[1, 3, 6, 9, 12, 18, 30],
          [1, 3, 6, 9, 12, 18, 25],
          [1, 3, 6, 9, 15, 25],
          [1, 3, 6, 10, 23]]

training_preselections: "fTPCsignalPi<1000 && abs(fNSigmaHe)<5 && fCosPA>0.99"
training_variables: ['fDcaV0Daug', 'fDcaHe', 'fDcaPi', 'fCosPA', 'fNSigmaHe']
extra_vars_used: ['fCentralityFT0C', 'fDecRad', 'fAvgClSizeCosLambda']
test_set_size: 0.5
bkg_fraction_max: 6
random_state: 42
hyperparams:
  max_depth: 6 # 5
  gamma: 2.0 # 0
  min_split_loss: 1.5 # 0.7
  learning_rate: 0.05
  n_estimators: 800
  min_child_weight: 3 # 3
  subsample: 0.70
  colsample_bytree: 0.73
  tree_method: 'hist'
  seed: 42
npoints_for_effi: 100